### ISSUE TITLE
TODO URG "Launch"

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/state-of-the-world#8]
#### Layout & design

- [x] confirm logo option
- [x] confirm intro graphic

#### Data

It appears your latest changes (25-30/3/) index values, HRC terms) were not done on the current tab/sheet ("ALL_countries") but on an old and incomplete sheet ("OLD_HRC_countries"). 

- [ ] confirm country HRC terms (specifically those marked orange in spreadsheet)
- [x] review RSF, TI, EIU index values
- [ ] confirm HRC term start dates (marked yellow in "hrc_terms" tab/sheet)

#### Application labels and text:

https://github.com/dumparkltd/state-of-the-world/blob/master/app/translations/en.json

Specifically: 

- [x] FAQs
  - [ ] ESR methodology
  - [ ] ESR assessment standards
  - [ ] CPR methodology
  - [ ] CPR uncertainty
  - [ ] different scale (country profile)
  - [ ] different year (country profile)

- [x] Country notes 
  - [ ] ESR no data
  - [ ] ESR no data for standard
  - [ ] CPR no data
  - [ ] change standard
  - [ ] standard automatically changed
  - [ ] ESR link to Rights Tracker profile for full data
  - [ ] CPR government respondent

- [x] Chart notes & tooltips
  - [ ] lack of country scores > representative 
  - [ ] ESR score tooltip (home)
  - [ ] CPR score tooltip (home)
  - [ ] ESR regional bias
  - [ ] CPR credible interval, long and short versions
  - [ ] ESR standard tooltip
  - [ ] CPR trend (CPR country ranking)
  - [ ] ESR trend (ESR country ranking)
  - [ ] ESR HI note (ESR country ranking)
  - [ ] CPR government respondents note (CPR country ranking)

- [x] Country about information
  - [x] HRC membership label for current term (Today)
  - [x] Consider adding max score or other explainer to add context to scores for indices (RSF, TI, EIU)
  - [ ] GDP: using only global best benchmark, we could drop the 2011 PPP measure and adjust the tooltip

- [x] Country names 
- [x] Rights descriptions
- [x] Indicator descriptions

#### Editorial content
https://github.com/dumparkltd/state-of-the-world-content/tree/master/_posts

- [x] methodology page, also overall structure
- [x] about page

#### Privacy

- [x] consider setting up Google Analytics: YES
- [ ] accordingly review privacy policy
- [x] accordingly review cookie dialogue messages

**Comment by tmfrnz** [comment]
## Tasks for including V-Dem scores

#### Data

- [x] confirm the metrics to use (and range of years)
- [ ] review v-dem classification to countries list
- [ ] add EIU democracy classification to countries list
- [ ] check data usage requirements

#### Editorial content

- [x] review and update methodology subpages https://github.com/dumparkltd/state-of-the-world-content/tree/master/_posts
- [x] review and update About page

#### Text & labels

- [x] review/update short descriptions for metrics (displayed in sidebar on metric view)
- [x] consider/confirm metric dropdown label in header (ie replacing "Rights" with "Metrics")
- [x] update home page title and intro text

**Comment by tmfrnz** [comment]
Suggestion for logo @dmprk: 

- globe
- hand
- magnifying glass
